<script>
    document.title = "about jordan"
</script>
<style>
    main#layout {
        font-family: "Arial", serif;
    }
</style>
<h1 class="title">about jordan</h1>
<p>
    You made it to the about page. Congrats!
</p>
<p>Here are some things I like.
    <ul>
<li>I like cats.</li>
<li>I like to dance.</li>
<li>I like to program things.</li>
    </ul>
</p>
<p>
    You can go back to the <a href="/index.html">homepage</a> if you'd like&hellip;
</p>