<!--{{title}}-->
About Jordan
<!--{{/title}}-->
<!--{{head}}-->
<title>About Jordan</title>
<meta
  name="description"
  content="Some interesting things about Jordan. Maybe you will learn something new!"
/>
<style>
  header > nav > ul > li.about {
    font-weight: 900;
  }
</style>
<!--{{/head}}-->
<!--{{main}}-->
<h1 class="title">About Jordan</h1>
<i>This about page is a work in progress.</i>
<p>You made it to the about page. Congrats!</p>
<p>Here are some things I like.</p>
<ul>
  <li>I like cats.</li>
  <li>I like to dance.</li>
  <li>I like to program things.</li>
</ul>
<p>You can go back to the <a href="/index.html">homepage</a> if you'd like&hellip;</p>
<!--{{/main}}-->
