<!--{{head}}-->
<title>Welcome to Jordan's Website</title>
<meta name="description" content="Jordan made a little routing website and wants you to check it out!">
<style>header > nav > ul > li.index {font-weight: bold;}</style>
<!--{{/head}}-->
<!--{{main}}-->
<h1 class="title">
    Jordan's Website
</h1>
<p>
    Hello and welcome to my website!
</p>
<p>
    I hope to show you many interesting things here.
</p>
<p>
    But I have not made them yet. So for now please enjoy what is on the page and we will deal with the rest later!
</p>
<!--{{/main}}-->