<!--head-->
<title>News</title>
<meta name="description" content="Just some news to peruse and bemuse.">
<!--/head-->
<style>
    main#layout a.secret {
        opacity: 0.2;
    }
</style>
<h1 class="title">News</h1>
<p>
    I have not published any news yet! Sorry.
</p>
<p>
    Please come back soon for news!
</p>
<p>
    You can go back to the <a href="/index.html">homepage</a> if you'd like&hellip;
</p>
<a class="secret" href="subpage.html">link to the secret news page</a>