<!--{{title}}-->
Secret Subpage!
<!--{{/title}}-->
<!--{{head}}-->
<title>A secret page!?</title>
<meta name="description" content="This is crazy. I'd never expect to find a secret page on Jordan's Website.">
<!--{{/head}}-->
<!--{{main}}-->
<h1 class="title">🤫</h1>
<p>you found the secret news page. ssh!</p>
<p><i>there was no secret news.</i></p>
<a href="index.html">go back to the news page?</a>
<!--{{/main}}-->